/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JuegoDelZapatoBlanco.GUI;
import JuegoDelZapatoBlanco.util.ListKids;
import javax.swing.JOptionPane;

/**
 *
 * @author Víctor Manuel
 */
public class Main extends javax.swing.JFrame {
    private ListKids listKids;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.listKids = new ListKids(txtAreGamTou);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreKidLis = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreZap = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreGamTou = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        regKid = new javax.swing.JMenu();
        Sta = new javax.swing.JMenu();
        exi = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juego del Zapatito Blanco");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setHorizontalScrollBar(null);

        txtAreKidLis.setEditable(false);
        txtAreKidLis.setBackground(new java.awt.Color(85, 22, 101));
        txtAreKidLis.setColumns(20);
        txtAreKidLis.setForeground(new java.awt.Color(255, 255, 255));
        txtAreKidLis.setRows(5);
        txtAreKidLis.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de niños", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        txtAreKidLis.setFocusable(false);
        jScrollPane1.setViewportView(txtAreKidLis);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 200, 160));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtAreZap.setEditable(false);
        txtAreZap.setBackground(new java.awt.Color(85, 22, 101));
        txtAreZap.setColumns(1);
        txtAreZap.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txtAreZap.setForeground(new java.awt.Color(255, 255, 255));
        txtAreZap.setRows(1);
        txtAreZap.setText("Zapatito Blanco\nZapatito Azul\n¡Dime cuántos años\ntienes tú!");
        txtAreZap.setAutoscrolls(false);
        txtAreZap.setBorder(null);
        txtAreZap.setFocusable(false);
        txtAreZap.setHighlighter(null);
        jScrollPane2.setViewportView(txtAreZap);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 200, 160));

        txtAreGamTou.setEditable(false);
        txtAreGamTou.setBackground(new java.awt.Color(85, 22, 101));
        txtAreGamTou.setColumns(20);
        txtAreGamTou.setForeground(new java.awt.Color(255, 255, 255));
        txtAreGamTou.setRows(5);
        txtAreGamTou.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Recorrido del juego", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        txtAreGamTou.setFocusable(false);
        jScrollPane3.setViewportView(txtAreGamTou);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 400, 143));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JuegoDelZapatoBlanco/GUI/fondoRegistro.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 380));

        jMenuBar1.setBackground(new java.awt.Color(85, 22, 101));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        regKid.setText("Registrar Niño");
        regKid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regKidMouseClicked(evt);
            }
        });
        jMenuBar1.add(regKid);

        Sta.setText("Empezar");
        Sta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StaMouseClicked(evt);
            }
        });
        jMenuBar1.add(Sta);

        exi.setText("Salir");
        exi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exiMouseClicked(evt);
            }
        });
        jMenuBar1.add(exi);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regKidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regKidMouseClicked
        options("Registrar Niño");
    }//GEN-LAST:event_regKidMouseClicked

    private void StaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StaMouseClicked
        listKids.firstMove();
    }//GEN-LAST:event_StaMouseClicked

    private void exiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exiMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exiMouseClicked
    private void options(String actionPerformed){
    switch(actionPerformed){
        case "Registrar Niño":
            String name = JOptionPane.showInputDialog(this, "Inserte el nombre del niño (a)", "Registro", JOptionPane.INFORMATION_MESSAGE);
            String sage = JOptionPane.showInputDialog(this, "inserte la edad del niño (a)", "Registro", JOptionPane.INFORMATION_MESSAGE);
                if(checkNumber(sage)){
                    short age = Short.parseShort(sage);
                    listKids.addKid(name, age);
                    this.txtAreKidLis.append(listKids.getLastOne().getName()+", "+listKids.getLastOne().getAge()+" años\n");
                    listKids.printList();
                }else{
                JOptionPane.showMessageDialog(this, "La edad tiene que ser un valor numérico entero","Error de Registro", JOptionPane.ERROR_MESSAGE);
                options(actionPerformed);
                }
                break;
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    public static boolean checkNumber(String string){
        boolean result;
        try{
        Integer.parseInt(string);
        result = true;
        } catch (NumberFormatException excepcion){
        result = false;
        }
        return result;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Sta;
    private javax.swing.JMenu exi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JMenu regKid;
    private javax.swing.JTextArea txtAreGamTou;
    private javax.swing.JTextArea txtAreKidLis;
    private javax.swing.JTextArea txtAreZap;
    // End of variables declaration//GEN-END:variables
}
